version: '3.5'

services:

  mysql-master:
    container_name: docker-mysql-replication-master-${APP_ENV:-dev}
    build:
      context: .
      target: ${APP_ENV:-dev}
      dockerfile: .docker/mysql/Dockerfile
      args:
        APP_ENV: ${APP_ENV:-dev}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-master.example}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - ${MYSQL_PORT_MASTER:-33059}:3306
    volumes:
      - ./.docker/mariadb/master.cnf:/etc/mysql/mariadb.conf.d/repl.cnf
      - ./.docker/mariadb/inner.cnf:/etc/mysql/mariadb.conf.d/inner.cnf
      - ./var/log/mysql:/var/log/mysql
      - dmre-mysqldb-master:/var/lib/mysql:rw

  adminer-master:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_SERVER_MASTER:-mysql-master}
    ports:
      - ${ADMINER_PORT_MASTER:-7979}:8080
    depends_on:
      - mysql-master

  mariadb-master:
    container_name: docker-mariadb-replication-master-${APP_ENV:-dev}
    build:
      context: .
      target: ${APP_ENV:-dev}
      dockerfile: .docker/mariadb/Dockerfile
      args:
        APP_ENV: ${APP_ENV:-dev}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-master.example}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - ${MYSQL_PORT_MASTER:-33060}:3306
    volumes:
      - ./.docker/mariadb/master.cnf:/etc/mysql/mariadb.conf.d/repl.cnf
      - ./var/log/mysql:/var/log/mysql
      - dmre-mariadb-master:/var/lib/mysql:rw

  pma-master:
    image: phpmyadmin/phpmyadmin:latest
    container_name: docker-mariadb-replication-pma-master-${APP_ENV:-dev}
    ports:
      - ${PMA_PORT_MASTER:-8080}:80
    environment:
      PMA_HOST: ${PMA_HOST_MASTER:-mariadb-master}
    depends_on:
      - mariadb-master

  mariadb-slave:
    container_name: docker-mariadb-replication-slave-${APP_ENV:-dev}
    build:
      context: .
      target: ${APP_ENV:-dev}
      dockerfile: .docker/mariadb/Dockerfile
      args:
        APP_ENV: ${APP_ENV:-dev}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-master.example}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - ${MYSQL_PORT_SLAVE:-33061}:3306
    volumes:
      - ./.docker/mariadb/slave.cnf:/etc/mysql/mariadb.conf.d/repl.cnf
      - ./var/log/mysql:/var/log/mysql
      - dmre-mariadb-slave:/var/lib/mysql:rw
    depends_on:
      - mariadb-master

  pma-slave:
    image: phpmyadmin/phpmyadmin:latest
    container_name: docker-mariadb-replication-pma-slave-${APP_ENV:-dev}
    ports:
      - ${PMA_PORT_SLAVE:-8181}:80
    environment:
      PMA_HOST: ${PMA_HOST_SLAVE:-mariadb-slave}
    depends_on:
      - mariadb-slave

volumes:
  dmre-mariadb-master:
  dmre-mysqldb-master:
  dmre-mariadb-slave: