version: '3.5'

services:

  mariadb:
    container_name: docker-mariadb-replication-${APP_ENV}
    build:
      context: .
      target: ${APP_ENV}
      dockerfile: .docker/mariadb/Dockerfile
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - dmre-mariadb:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: docker-mariadb-replication-pma-${APP_ENV}
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: ${PMA_HOST}

volumes:
  dmre-mariadb: